// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAHAg_LTISDFXumEKvShHbDeGvVXiJEc',
    appId: '1:868126607741:web:201d3b941a388620352414',
    messagingSenderId: '868126607741',
    projectId: 'frogout-a12bb',
    authDomain: 'frogout-a12bb.firebaseapp.com',
    storageBucket: 'frogout-a12bb.appspot.com',
    measurementId: 'G-4HP6DSHG6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWlfaXi9zC4iGDlWdBevwSWZ-nzd4OVc',
    appId: '1:868126607741:android:6f2c14e15e15df44352414',
    messagingSenderId: '868126607741',
    projectId: 'frogout-a12bb',
    storageBucket: 'frogout-a12bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2t3a1fS0A4_h50uhAV2ma8ZkYhFLeP24',
    appId: '1:868126607741:ios:0715073f83ac5cd0352414',
    messagingSenderId: '868126607741',
    projectId: 'frogout-a12bb',
    storageBucket: 'frogout-a12bb.appspot.com',
    iosClientId: '868126607741-js1aecjpb80i3m3ospphbukng35f6m9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frogout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2t3a1fS0A4_h50uhAV2ma8ZkYhFLeP24',
    appId: '1:868126607741:ios:0715073f83ac5cd0352414',
    messagingSenderId: '868126607741',
    projectId: 'frogout-a12bb',
    storageBucket: 'frogout-a12bb.appspot.com',
    iosClientId: '868126607741-js1aecjpb80i3m3ospphbukng35f6m9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.frogout',
  );
}
